heat_template_version: 2013-05-23
description: Test for CloudConfig resource
parameters:
  flavor:
    type: string
    default: m1.heat
  key:
    type: string
    default: demo
  image:
    type: string
    default: fedora-heat-test-image
  availability_zone:
    type: string
    default: nova
  public_net:
    type: string
    default: public
  private_net:
    type: string
    default: private
  userparam:
    type: string
    default: SomeMoreData

resources:

  port:
    type: OS::Neutron::Port
    properties:
      network: { get_param: private_net }

  server_config:
    type: OS::Heat::CloudConfig
    properties:
      cloud_config:
        write_files:
        - path: /etc/check.conf
          owner: root:root
          permissions: '0644'
          content:
            str_replace:
              template: |
                [DEFAULT]
                param = $USERPARAM
              params:
                $USERPARAM: { get_param: userparam }
        runcmd:
          - whoami > /home/fedora/whowasi.txt

  server:
    type: OS::Nova::Server
    properties:
      image: { get_param: image }
      flavor: { get_param: flavor }
      key_name: { get_param: key }
      availability_zone: { get_param: availability_zone }
      networks:
        - port: { get_resource: port }
      user_data_format: RAW
      user_data: { get_resource: server_config }

  float_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: { get_param: public_net }

  float_ip_assoc:
    type: OS::Neutron::FloatingIPAssociation
    properties:
      floatingip_id: { get_resource: float_ip }
      port_id: { get_resource: port }

outputs:
  public_ip:
    description: Public IP of the instance
    value: { get_attr: [ float_ip, floating_ip_address ] }
